---
- name: Configure FortiGate via SSH (with raw module)
  hosts: fortigate
  gather_facts: false

  vars:
    vpn:
      name: "from_200_to_129"
      interface: "port1"
      peertype: "any"
      local_interface: "port2"
      local_subnet: "10.10.10.0 255.255.255.0"
      remote_subnet: "20.20.20.0 255.255.255.0"
      remote_gw: "192.168.11.140"
      psk: "test12345"
      comment: "VPN: from 200 to 129 [Created by Ansible]"
      proposal: "des-md5"
      phase2_proposal: "des-md5"
      
  tasks:
    - name: Render CLI config into a local file
      ansible.builtin.template:
        src: template/ipsectunnel.j2
        dest: /tmp/fortigate_config.txt
      delegate_to: localhost

    - name: Read generated config content
      ansible.builtin.slurp:
        src: /tmp/fortigate_config.txt
      register: slurped_config
      delegate_to: localhost

    - name: Push CLI config to FortiGate
      ansible.builtin.raw: "{{ slurped_config['content'] | b64decode }}"
      register: result

    - name: Display CLI result
      ansible.builtin.debug:
        var: result.stdout_lines