---
- name: Configure FortiGate via SSH (with raw module)
  hosts: fortigate
  gather_facts: false

  vars:
    vpn:
      name: "{{ vpn.name }}"
      interface: "{{ vpn.interface }}"
      peertype: "{{ vpn.peertype }}"
      local_interface: "{{ vpn.local_interface }}"
      local_subnet: "{{ vpn.local_subnet }}"
      remote_subnet: "{{ vpn.remote_subnet }}"
      remote_gw: "{{ vpn.remote_gw }}"
      psk: "{{ vpn.psk }}"
      comment: "{{ vpn.comment }}"
      proposal: "{{ vpn.proposal }}"
      phase2_proposal: "{{ vpn.phase2_proposal }}"

  tasks:
    - name: Show vpn variables (for debugging)
      debug:
        msg:
          - "VPN Name: {{ vpn.name }}"
          - "VPN Interface: {{ vpn.interface }}"
          - "VPN Local Subnet: {{ vpn.local_subnet }}"
          - "VPN Remote Subnet: {{ vpn.remote_subnet }}"
  tasks:
    - name: Render CLI config into a local file
      ansible.builtin.template:
        src: template/ipsectunnel.j2
        dest: /tmp/fortigate_config.txt
      delegate_to: localhost

    - name: Read generated config content
      ansible.builtin.slurp:
        src: /tmp/fortigate_config.txt
      register: slurped_config
      delegate_to: localhost

    - name: Push CLI config to FortiGate
      ansible.builtin.raw: "{{ slurped_config['content'] | b64decode }}"
      register: result

    - name: Display CLI result
      ansible.builtin.debug:
        var: result.stdout_lines