- name: Configure firewall policy on FortiGate
  hosts: fortigate
  gather_facts: false
  tasks:
    - name: Configure policy FROM LAN TO WAN
      fortinet.fortios.fortios_firewall_policy:
        vdom: "root"
        state: "present"
        firewall_policy:
          policyid: 1
          name: "FROM LAN TO WAN"
          srcintf:
            - name: "port2"
          dstintf:
            - name: "port1"
          action: "accept"
          srcaddr:
            - name: "all"
          dstaddr:
            - name: "all"
          schedule: "always"
          service:
            - name: "ALL"
          nat: "enable"