- name: Test pushing file from AWX to local machine
  hosts: all
  become: true

  tasks:
    - name: Ensure target directory exists
      file:
        path: /home/dhia/Desktop/createfirewall/audit_rules
        state: directory
        mode: '0755'

    - name: Create test file on local machine
      copy:
        dest: /home/dhia/Desktop/createfirewall/audit_rules/test_awx.txt
        content: "Hello from AWX!"
