- name: Save 'Hello' to a file
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    output_file: "/home/dhia/Desktop/createfirewall/audit_rules/hello.txt"

  tasks:
    - name: Ensure output directory exists
      file:
        path: "/home/dhia/Desktop/createfirewall/audit_rules"
        state: directory
        mode: '0755'
    
    - name: Save 'Hello' to the file
      copy:
        content: "Hello"
        dest: "{{ output_file }}"
        mode: '0644'
