- name: SCP file to local machine from AWX
  hosts: localhost
  gather_facts: no
  vars:
    local_machine_ip: "192.168.11.209"
    local_machine_user: "dhia"
    local_machine_target_dir: "/home/dhia/Desktop/createfirewall/audit_rules"
    test_file: "/tmp/hello_awx.txt"

  tasks:
    - name: Create test file in AWX controller
      ansible.builtin.shell: echo "Hello from AWX" > {{ test_file }}

    - name: SCP test file to local machine
      ansible.builtin.command: >
        scp {{ test_file }} {{ local_machine_user }}@{{ local_machine_ip }}:{{ local_machine_target_dir }}/
      delegate_to: localhost
