- name: Simple SCP test from AWX to local machine
  hosts: localhost
  gather_facts: no
  vars:
    local_machine_ip: "192.168.11.209"
    local_machine_user: "dhia"
    local_machine_target_dir: "/home/dhia/Desktop/createfirewall/audit_rules"
    test_file: "/home/dhia/Desktop/createfirewall/hello.txt"

  tasks:
    - name: Create a test file on AWX controller
      copy:
        content: "Hello from AWX!"
        dest: "{{ test_file }}"

    - name: Transfer file to local machine via SCP
      command: >
        scp {{ test_file }} {{ local_machine_user }}@{{ local_machine_ip }}:{{ local_machine_target_dir }}/
      delegate_to: localhost
