- name: Test saving a file to my local machine via AWX
  hosts: localhost
  gather_facts: no
  vars:
    local_machine_ip: "192.168.11.209"      # Your local machine's IP
    local_machine_user: "dhia"              # Your local machine's SSH user
    local_machine_target_dir: "/home/dhia/Desktop/createfirewall/audit_rules"
    test_file: "/tmp/hello.txt"

  tasks:
    - name: Create a test file on the controller
      copy:
        dest: "{{ test_file }}"
        content: "Hello from AWX!\n"

    - name: Copy file with SCP ignoring host key
      command: >
        scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null /tmp/hello.txt dhia@192.168.11.209:/home/dhia/
      delegate_to: localhost
