- name: Create and copy a file from AWX to your local machine
  hosts: localhost
  gather_facts: false
  vars:
    local_machine_ip: "192.168.11.209"
    local_machine_user: "dhia"
    scp_password: "96808538"
    local_machine_path: "/home/dhia/Desktop/createfirewall/audit_rules"
    file_name: "hello_awx.txt"
    file_content: "Hello from AWX via SCP!"
    awx_output_dir: "/home/dhia/Desktop/createfirewall/audit_rules"  # <== Use a writable directory in AWX

  tasks:
    - name: Create the test file in /runner directory
      copy:
        content: "{{ file_content }}"
        dest: "{{ awx_output_dir }}/{{ file_name }}"

    - name: Copy file to your local machine via SCP
      ansible.builtin.command: >
        sshpass -p {{ scp_password }} scp -o StrictHostKeyChecking=no
        {{ awx_output_dir }}/{{ file_name }}
        {{ local_machine_user }}@{{ local_machine_ip }}:{{ local_machine_path }}/
      delegate_to: localhost
