- name: Create file in AWX and copy to local machine via SCP
  hosts: localhost
  gather_facts: false
  vars:
    file_content: "Hello from AWX"
    file_name: "test_awx.txt"
    awx_output_dir: "/tmp"  # AWX can write here
    local_machine_ip: "192.168.11.209"
    local_machine_user: "dhia"
    local_machine_path: "/home/dhia/Desktop/createfirewall/audit_rules"
    scp_password: "96808538"

  tasks:

    - name: Create file on AWX host
      copy:
        content: "{{ file_content }}"
        dest: "{{ awx_output_dir }}/{{ file_name }}"
      delegate_to: localhost

    - name: Install sshpass (required for password-based SCP)
      package:
        name: sshpass
        state: present
      become: true
      delegate_to: localhost

    - name: Copy file to local machine via SCP
      ansible.builtin.command: >
        sshpass -p {{ scp_password }} scp -o StrictHostKeyChecking=no {{ awx_output_dir }}/{{ file_name }}
        {{ local_machine_user }}@{{ local_machine_ip }}:{{ local_machine_path }}/
      delegate_to: localhost
